// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

// CreateUserReq 创建用户请求体
type CreateUserReq struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}

// UserIdReq 获取用户时的路径参数
type UserIdReq struct {
	Id string `path:"id"`
}

// User 用户数据结构
type User struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}

// UploadResp 上传文件的返回结果
type UploadResp struct {
	Message string `json:"message"`
	Path    string `json:"path"`
}
